apiVersion: v2
name: cluster-api-provider-hetzner
description: A Helm chart for Cluster API Provider Hetzner
type: application
version: 0.3.0
appVersion: "1.0.3"
annotations:
  cluster.x-k8s.io/provider: infrastructure-hetzner
  cluster.x-k8s.io/v1beta1: v1beta1
