apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "cluster.name" . }}
  namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
  {{- if .Values.clusterLabels }}
  labels: {{- toYaml .Values.clusterLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.clusterAnnotations }}
  annotations: {{- toYaml .Values.clusterAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.clusterNetwork }}
  clusterNetwork:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0sControlPlane
    name: {{ include "k0scontrolplane.name" . }}
    namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KubevirtCluster
    name: {{ include "cluster.name" . }}
    namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
