apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: {{ include "k0sworkerconfigtemplate.name" . }}
  namespace: {{ .Values.cluster.namespace }}
spec:
  template:
    spec:
      version: {{ .Values.k0s.version }}
      preStartCommands:
      {{- with .Values.worker.preStartCommands }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
