apiVersion: v1
kind: ConfigMap
metadata:
  name: driver-config
  namespace: {{ .Release.Namespace }}
data:
  infraClusterNamespace: {{ .Values.infraClusterNamespace }}
  infraClusterLabels: {{ .Values.infraClusterLabels }}